inherit_from: .rubocop_todo.yml

require:
  - standard
  - rubocop-rspec
  - rubocop-rake

inherit_gem:
  standard: config/base.yml

Capybara/ClickLinkOrButtonStyle: # new in 2.19
  Enabled: false
Capybara/MatchStyle: # new in 2.17
  Enabled: false
Capybara/NegationMatcher: # new in 2.14
  Enabled: false
Capybara/RedundantWithinFind: # new in 2.20
  Enabled: false
Capybara/SpecificActions: # new in 2.14
  Enabled: false
Capybara/SpecificFinders: # new in 2.13
  Enabled: false
Capybara/SpecificMatcher: # new in 2.12
  Enabled: false
Capybara/RSpec/HaveSelector: # new in 2.19
  Enabled: false
Capybara/RSpec/PredicateMatcher: # new in 2.19
  Enabled: false
FactoryBot/AssociationStyle: # new in 2.23
  Enabled: false
FactoryBot/ConsistentParenthesesStyle: # new in 2.14
  Enabled: false
FactoryBot/FactoryAssociationWithStrategy: # new in 2.23
  Enabled: false
FactoryBot/FactoryNameStyle: # new in 2.16
  Enabled: false
FactoryBot/IdSequence: # new in <<next>>
  Enabled: false
FactoryBot/RedundantFactoryOption: # new in 2.23
  Enabled: false
FactoryBot/SyntaxMethods: # new in 2.7
  Enabled: false
RSpec/BeEmpty: # new in 2.20
  Enabled: true
RSpec/BeEq: # new in 2.9.0
  Enabled: true
RSpec/BeNil: # new in 2.9.0
  Enabled: true
RSpec/ChangeByZero: # new in 2.11
  Enabled: true
RSpec/ContainExactly: # new in 2.19
  Enabled: true
RSpec/DuplicatedMetadata: # new in 2.16
  Enabled: true
RSpec/EmptyMetadata: # new in 2.24
  Enabled: true
RSpec/Eq: # new in 2.24
  Enabled: true
RSpec/ExcessiveDocstringSpacing: # new in 2.5
  Enabled: true
RSpec/IdenticalEqualityAssertion: # new in 2.4
  Enabled: true
RSpec/IndexedLet: # new in 2.20
  Enabled: true
RSpec/MatchArray: # new in 2.19
  Enabled: true
RSpec/MetadataStyle: # new in 2.24
  Enabled: true
RSpec/NoExpectationExample: # new in 2.13
  Enabled: true
RSpec/PendingWithoutReason: # new in 2.16
  Enabled: true
RSpec/ReceiveMessages: # new in 2.23
  Enabled: true
RSpec/RedundantAround: # new in 2.19
  Enabled: true
RSpec/SkipBlockInsideExample: # new in 2.19
  Enabled: true
RSpec/SortMetadata: # new in 2.14
  Enabled: true
RSpec/SpecFilePathFormat: # new in 2.24
  Enabled: true
RSpec/SpecFilePathSuffix: # new in 2.24
  Enabled: true
RSpec/SubjectDeclaration: # new in 2.5
  Enabled: true
RSpec/VerifiedDoubleReference: # new in 2.10.0
  Enabled: true
RSpec/Rails/AvoidSetupHook: # new in 2.4
  Enabled: true
RSpec/Rails/HaveHttpStatus: # new in 2.12
  Enabled: true
RSpec/Rails/InferredSpecType: # new in 2.14
  Enabled: true
RSpec/Rails/MinitestAssertions: # new in 2.17
  Enabled: true
RSpec/Rails/NegationBeValid: # new in 2.23
  Enabled: true
RSpec/Rails/TravelAround: # new in 2.19
  Enabled: true
